services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: done
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
